<script lang="ts">
	import GameGrid from './GameGrid.svelte'

	let { data } = $props()

	let gridMap = [
		{
			map: [
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0, room: 12 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 0, room: 2 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0, room: 3 },
					{ tile: 0, room: 3 },
					{ tile: 0, room: 3 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 3 },
					{ tile: 0, room: 3 },
					{ tile: 0, room: 3 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 0, room: 15 },
					{ tile: 1 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 1 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 3 },
					{ tile: 0, room: 3 },
					{ tile: 0, room: 3 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 1 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 0, room: 8 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 0, room: 1 },
					{ tile: 1 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 0, room: 9 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 0, room: 7 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 0, room: 13 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 0, room: 11 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 0, room: 4 },
					{ tile: 1 },
					{ tile: 0, room: 16 },
					{ tile: 0, room: 16 },
					{ tile: 0, room: 16 },
					{ tile: 0 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 0 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 1 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 0, room: 6 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 16 },
					{ tile: 0, room: 16 },
					{ tile: 0, room: 16 },
					{ tile: 1 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 1 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 1 },
					{ tile: 0 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 10 },
					{ tile: 0, room: 10 },
					{ tile: 0, room: 10 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 16 },
					{ tile: 0, room: 16 },
					{ tile: 0, room: 16 },
					{ tile: 1 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 1 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 10 },
					{ tile: 0, room: 10 },
					{ tile: 0, room: 10 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 1 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 1 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 10 },
					{ tile: 0, room: 10 },
					{ tile: 0, room: 10 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 0, room: 5 },
					{ tile: 1 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 0, room: 18 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 0, room: 17 },
					{ tile: 1 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 0, room: 14 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				],
				[
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 },
					{ tile: 1 }
				]
			],
			rooms: [
				{ h: 7, w: 5, row: 4, col: 20 },
				{ h: 5, w: 7, row: 2, col: 10 },
				{ h: 3, w: 3, row: 6, col: 34 },
				{ h: 3, w: 5, row: 18, col: 4 },
				{ h: 5, w: 3, row: 20, col: 14 },
				{ h: 7, w: 7, row: 14, col: 30 },
				{ h: 3, w: 7, row: 12, col: 4 },
				{ h: 3, w: 7, row: 8, col: 8 },
				{ h: 3, w: 5, row: 8, col: 26 },
				{ h: 3, w: 3, row: 22, col: 2 },
				{ h: 3, w: 7, row: 16, col: 20 },
				{ h: 3, w: 5, row: 2, col: 28 },
				{ h: 3, w: 5, row: 16, col: 12 },
				{ h: 3, w: 7, row: 22, col: 30 },
				{ h: 7, w: 5, row: 2, col: 2 },
				{ h: 3, w: 3, row: 20, col: 10 },
				{ h: 5, w: 5, row: 20, col: 24 },
				{ h: 5, w: 3, row: 20, col: 18 }
			],
			config: { rooms: 18, rows: 27, cols: 39, tileSize: 20, gridGap: 1 }
		}
	]
</script>

<section class="page-layer nwp game-bg">
	<article class="content">
		<h1>{data.title}</h1>
		<p>Maps: {data.maps.length}</p>
	</article>

	<!-- <GameGrid {gridMap}></GameGrid> -->
</section>
